# Generated by Django 2.2.10 on 2020-02-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentsRollNumber', models.IntegerField(unique=True)),
                ('studentsRollOfMonth', models.IntegerField(unique_for_date=True)),
                ('studentfName', models.CharField(max_length=100)),
                ('studentlName', models.CharField(max_length=100)),
                ('studentEmail', models.EmailField(max_length=100)),
                ('studentSchoolName', models.CharField(max_length=100)),
                ('studentClassName', models.CharField(max_length=100)),
                ('studenSectionName', models.CharField(max_length=100)),
                ('student_telMarks', models.IntegerField()),
                ('student_hindiMarks', models.IntegerField()),
                ('student_englishMarks', models.IntegerField()),
                ('student_mathMarks', models.IntegerField()),
                ('student_science', models.IntegerField()),
                ('student_social', models.IntegerField()),
            ],
        ),
    ]
