# Generated by Django 2.2.10 on 2020-02-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdata',
            name='studentsRollOfMonth',
            field=models.IntegerField(),
        ),
    ]
